name = "eeprom_i2c_examples"
description = "Shiny new project"
version = "0.0.0"
licenses = "BSD-3-Clause"

authors = ["Holger Rodriguez"]
maintainers = ["Holger Rodriguez <github@roseng.ch>"]
maintainers-logins = ["hgrodriguez"]
tags = ["embedded", "rp2040"]
website = "https://github.com/hgrodriguez/eeprom_i2c"

executables = ["eeprom_i2c_examples"]
[[depends-on]]  # Added by alr
pico_bsp = "^1.1.0"  # Added by alr

[[depends-on]]  # Added by alr
gnat_arm_elf = "^11.2.3"  # Added by alr
[[depends-on]]  # Added by alr
edc_client = "^1.3.3"  # Added by alr
[[depends-on]]  # Added by alr
itsybitsy_bsp = "~0.0.3"  # Added by alr
